package model;

public enum Permeability {

	BLOCKING, // FOR WALLS
	PENETRABLE, //FOR THE WAY
	TOUCHABLE, // FOR THE CRYSTALS
	OPENGATE, //FOR THE DOORS
	KILLING, // FOR THE MONSTERS
	POWER, // FOR LORANN
	
	
}
